# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotometricFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=100)),
                ('cwl', models.FloatField()),
                ('width', models.FloatField()),
                ('lambda_b', models.FloatField()),
                ('lambda_e', models.FloatField()),
                ('mvega', models.FloatField()),
                ('fvega', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SpectralTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VPHSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('fwhm', models.FloatField()),
                ('dispersion', models.FloatField()),
                ('deltab', models.FloatField()),
                ('lambdac', models.FloatField()),
                ('relatedband', models.CharField(max_length=10)),
                ('lambda_b', models.FloatField()),
                ('lambda_e', models.FloatField()),
                ('specconf', models.CharField(max_length=10)),
            ],
        ),
    ]
